# fly.toml app configuration file generated for ftest on 2023-08-23T21:23:47+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ftest"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.http_options.response.headers]
  fly-request-id = false
  fly-wasnt-here = "yes, it was"
  multi-valued = ["value1", "value2"]
